### ISSUE TITLE
ArgumentError when creating empty job via SauceWhisk::Job.new job_id

### ISSUE THREAD

**Issue by travis-fillmore-ck** [saucelabs/sauce_whisk#9]
Attempting to create a new 'empty' job, per the documentation,

``` ruby
job = SauceWhisk::Job.new job_id
```

results in the following error:

```
 ArgumentError:
  invalid range "m-d" in string transliteration
  # /usr/local/rvm/gems/ruby-1.9.3-p194/gems/sauce_whisk-0.0.10/lib/sauce_whisk/jobs.rb:80:in `delete'
  # /usr/local/rvm/gems/ruby-1.9.3-p194/gems/sauce_whisk-0.0.10/lib/sauce_whisk/jobs.rb:80:in `initialize'
```

**Comment by DylanLacey** [comment]
Closing due to age.
